### PR TITLE
FreeC interpreter example

### PR DESCRIPTION
**Pull request by aryairani**
FreeC code corresponding to https://forums.manning.com/posts/list/37587.page

Feel free to merge or discard, or let me know if you want to chat more!

### CODE REVIEW

**Comment by debasishg** [comment]
Thanks a lot for the PR .. I plan to play around with it over the weekend and then merge .. The reason I went the Functor way is to avoid explaining stuff like CoYoneda & natural transformation. But this makes a much cleaner implementation and hence possibly I will use this. Thanks again ..

**Comment by refried** [comment]
If you want to give me an acknowledgement in the book, I'll parade it around to all my friends ;-)

**Comment by debasishg** [comment]
Absolutely .. that goes without saying .. I will give proper acknowledgement and attribution ..

**Comment by refried** [comment]
I was half joking, but that would be great!

**Comment by debasishg** [comment]
But I am not joking :-) ..

**Comment by debasishg** [comment]
merged in branch `freec-scalaz-7.2.x`. Will move the branch to `master` when the text syncs up with the implementation. Thanks for the PR ..

**Pull request merged**
